[tool.poetry]
name = "strokealert"
version = "0.1.0"
description = "stroke Alert prototype"
authors = ["Game <jeerasakananta@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]

python = "^3.12"
langchain="0.3.21"
openai="1.69.0"
fastapi="0.115.12"
uvicorn="0.34.0"
requests="2.32.3"
python-dotenv="1.1.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]

requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
